-- Projeto Final - BANCO: SISTEMA DE LOCACAO DE VEiCULOS
-- Guilherme Ferreira Pinheiro Guimaraes


CREATE DATABASE IF NOT EXISTS LOCADORA;
USE LOCADORA;

-- TABELA CLIENTE
CREATE TABLE CLIENTE (
    IDCLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(200) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    EMAIL VARCHAR(120),
    TELEFONE VARCHAR(20),
    DATACADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    ENDERECO VARCHAR(255),
    DATANASCIMENTO DATE,
    STATUSCLIENTE ENUM('ATIVO','INATIVO') DEFAULT 'ATIVO'
);




-- TABELA FILIAL
CREATE TABLE FILIAL (
    IDFILIAL INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(200) NOT NULL,
    CIDADE VARCHAR(255) NOT NULL,
    UF CHAR(2) NOT NULL,
    ENDERECO VARCHAR(255),
    TELEFONE VARCHAR(20),
    HORARIOABERTURA TIME,
    HORARIOFECHAMENTO TIME
);



-- TABELA FUNCIONARIO
CREATE TABLE FUNCIONARIO (
    IDFUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(200) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    EMAIL VARCHAR(120),
    TELEFONE VARCHAR(20),
    CARGO VARCHAR(80),
    DATACONTRATACAO DATE,
    STATUSFUNCIONARIO ENUM('ATIVO','INATIVO') DEFAULT 'ATIVO',
    IDFILIAL INT NOT NULL,
    FOREIGN KEY (IDFILIAL) REFERENCES FILIAL(IDFILIAL)
);


-- TABELA CATEGORIA
CREATE TABLE CATEGORIA (
    IDCATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
	TIPOCATEGORIA ENUM('ECONOMICO','MEDIO PADRAO','LUXO')

);



-- TABELA VEICULO
CREATE TABLE VEICULO (
    IDVEICULO INT AUTO_INCREMENT PRIMARY KEY,
    PLACA CHAR(7) NOT NULL UNIQUE,
    RENAVAM CHAR(11) NOT NULL UNIQUE,
    MARCA VARCHAR(100) NOT NULL,
    MODELO VARCHAR(100) NOT NULL,
    ANO INT NOT NULL,
    COR VARCHAR(30),
    KMATUAL INT DEFAULT 0,
    STATUSVEICULO ENUM('DISPONIVEL','EMUSO','MANUTENCAO','TRANSFERENCIA') DEFAULT 'DISPONIVEL',
    IDCATEGORIA INT NOT NULL,
    IDFILIAL INT NOT NULL,
    FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA),
    FOREIGN KEY (IDFILIAL) REFERENCES FILIAL(IDFILIAL)
);




-- TABELA RESERVA
CREATE TABLE RESERVA (
    IDRESERVA INT AUTO_INCREMENT PRIMARY KEY,
    DATAINICIO DATETIME NOT NULL,
    DATAFIM DATETIME NOT NULL,
    STATUSRESERVA ENUM('ATIVA','CANCELADA','CONVERTIDA') DEFAULT 'ATIVA',
    DATACRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    IDCLIENTE INT NOT NULL,
    IDVEICULO INT NOT NULL,
    IDFILIAL INT NOT NULL,
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE),
    FOREIGN KEY (IDVEICULO) REFERENCES VEICULO(IDVEICULO),
    FOREIGN KEY (IDFILIAL) REFERENCES FILIAL(IDFILIAL)
);



-- TABELA LOCACAO
CREATE TABLE LOCACAO (
    IDLOCACAO INT AUTO_INCREMENT PRIMARY KEY,
    DATARETIRADA DATETIME NOT NULL,
    KMDERETIRADA INT NOT NULL,
    DATADEVOLUCAO DATETIME,
    HMDEDEVOLUCAO INT,
    VALORDIARIA DECIMAL(10,2),
    TAXAS DECIMAL(10,2),
    MULTAS DECIMAL(10,2),
    VALORFINAL DECIMAL(10,2),
    STATUSLOCACAO ENUM('ABERTA','FINALIZADA','CANCELADA') DEFAULT 'ABERTA',
    IDRESERVA INT NULL,
    IDCLIENTE INT NOT NULL,
    IDVEICULO INT NOT NULL,
    IDFILIAL INT NOT NULL,
    FOREIGN KEY (IDRESERVA) REFERENCES RESERVA(IDRESERVA),
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE),
    FOREIGN KEY (IDVEICULO) REFERENCES VEICULO(IDVEICULO),
    FOREIGN KEY (IDFILIAL) REFERENCES FILIAL(IDFILIAL)
);



-- TABELA TARIFA 
CREATE TABLE TARIFA (
    IDTARIFA INT AUTO_INCREMENT PRIMARY KEY,
	INICIODEVIGENCIA DATE NOT NULL,
    FIMDEVIGENCIA DATE NULL,
    VALORDIARIA DECIMAL(10,2) NOT NULL,
    DESCTARIFA VARCHAR(255),
    IDCATEGORIA INT NOT NULL,
    FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA)
);



-- TABELA TAXA 
CREATE TABLE TAXA (
    IDTAXA INT AUTO_INCREMENT PRIMARY KEY,
    DESCTAXA VARCHAR(255) NOT NULL,
    VALORFIXO DECIMAL(10,2),
    PERCENTUAL DECIMAL(5,2),
    APLICAVEL VARCHAR(40),  
    IDFILIAL INT NOT NULL,
    FOREIGN KEY (IDFILIAL) REFERENCES FILIAL(IDFILIAL)
);



-- TABELA PAGAMENTO
CREATE TABLE PAGAMENTO (
    IDPAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
    DATAPAGAMENTO DATETIME NOT NULL,
    METODO ENUM('PIX','CREDITO','DEBITO','DINHEIRO'),
    VALORPAGO DECIMAL(10,2) NOT NULL,
    STATUSPAGAMENTO ENUM('PENDENTE','PAGO','ESTORNADO') DEFAULT 'PENDENTE',
	IDLOCACAO INT NOT NULL,
    FOREIGN KEY (IDLOCACAO) REFERENCES LOCACAO(IDLOCACAO)
);



-- TABELA MOVIMENTO_VEICULO 
CREATE TABLE MOVIMENTO_VEICULO (
    IDMOVIMENTO_VEICULO INT AUTO_INCREMENT PRIMARY KEY,
    DATAMOVIMENTO_VEICULO DATETIME NOT NULL,
    TIPOMOVIMENTO ENUM('TRANSFERENCIA','DISPONIBILIZACAO','RETORNO','MANUTENCAO'),
    DESCMOVIMENTO VARCHAR(255),
    IDVEICULO INT NOT NULL,
    IDFILIAL INT,
    IDLOCACAO INT,
    FOREIGN KEY (IDVEICULO) REFERENCES VEICULO(IDVEICULO),
    FOREIGN KEY (IDFILIAL) REFERENCES FILIAL(IDFILIAL),
    FOREIGN KEY (IDLOCACAO) REFERENCES LOCACAO(IDLOCACAO)
);



-- TABELA MANUTENCAO
CREATE TABLE MANUTENCAO (
    IDMANUTENCAO INT AUTO_INCREMENT PRIMARY KEY,
    DATAMANUTENCAO DATE NOT NULL,
    TIPOMANUTENCAO VARCHAR(255),
    CUSTO DECIMAL(10,2),
    KMDEREFERENCIA INT,
    FORNECEDOR VARCHAR(120),
    DESCMANUNTECAO VARCHAR(255),
	IDVEICULO INT NOT NULL,
    FOREIGN KEY (IDVEICULO) REFERENCES VEICULO(IDVEICULO)
);




