
-- Projeto Final - BANCO: SISTEMA DE LOCACAO DE VEiCULOS
-- Guilherme Ferreira Pinheiro Guimaraes
--  TRIGGERS DE AUDITORIA

USE LOCADORA;


 -- TABELA DE AUDITORIA
CREATE TABLE IF NOT EXISTS AUDITORIA_LOCACAO (
    IDAUDIT INT AUTO_INCREMENT PRIMARY KEY,
    IDLOCACAO INT,
    OPERACAO VARCHAR(20),
    DATAHORA DATETIME,
    USUARIO VARCHAR(50)
);



 -- TRIGGERS 

DELIMITER //

-- Auditoria de INSERT na LOCACAO 
CREATE TRIGGER trg_audita_locacao_insert
BEFORE INSERT ON LOCACAO
FOR EACH ROW
BEGIN
    INSERT INTO AUDITORIA_LOCACAO(IDLOCACAO, OPERACAO, DATAHORA, USUARIO)
    VALUES (NEW.IDLOCACAO, 'INSERT', NOW(), CURRENT_USER());
END //

-- Auditoria de UPDATE na LOCACAO 
CREATE TRIGGER trg_audita_locacao_update
BEFORE UPDATE ON LOCACAO
FOR EACH ROW
BEGIN
    INSERT INTO AUDITORIA_LOCACAO(IDLOCACAO, OPERACAO, DATAHORA, USUARIO)
    VALUES (OLD.IDLOCACAO, 'UPDATE', NOW(), CURRENT_USER());
END //

DELIMITER ;


