
-- Projeto Final - BANCO: SISTEMA DE LOCACAO DE VEiCULOS
-- Guilherme Ferreira Pinheiro Guimaraes
-- 04_dml_update_delete

USE LOCADORA;

-- 04_dml_update_delete.sql com exemplos: correção de cadastro, cancelamento de reserva, baixa de veículo.



-- UPDATE de Cadastro do CLIENTE

-- UPDATE NOME DO CLIENTE
UPDATE CLIENTE
SET NOME = 'Mariana Oliveira Santos'
WHERE CPF = '123.456.789-01';


-- UPDATE EMAIL DO CLIENTE
UPDATE CLIENTE
SET EMAIL = 'mariana.santos@gmail.com'
WHERE CPF = '123.456.789-01';


-- UPDATE TELEFONE DO CLIENTE
UPDATE CLIENTE
SET TELEFONE = '(61) 98888-7777'
WHERE IDCLIENTE = 3;


--  UPDATE ENDERECO DO CLIENTE
UPDATE CLIENTE
SET ENDERECO = 'QNL 18 Conjunto C Casa 12'
WHERE IDCLIENTE = 5;


-- UPDATE DE STATUS DO CLIENTE
UPDATE CLIENTE
SET STATUSCLIENTE = 'INATIVO'
WHERE IDCLIENTE = 8;





--  COMANDOS UPDATE DE RESERVA DE VEICULO 
-- CANCELAR a reserva que antes estva ativa
UPDATE RESERVA
SET STATUSRESERVA = 'CANCELADA'
WHERE IDRESERVA = 4;


-- PRORROGAR o fim da reserva
UPDATE RESERVA
SET DATAFIM = DATE_ADD(DATAFIM, INTERVAL 2 DAY)
WHERE IDRESERVA = 8;


-- ALTERAR veículo da reserva
UPDATE RESERVA
SET IDVEICULO = 12
WHERE IDRESERVA = 6;


-- ATUALIZAR filial de retirada
UPDATE RESERVA
SET IDFILIAL = 2
WHERE IDRESERVA = 7;


-- ATUALIZAR reserva em locacao - status
UPDATE RESERVA
SET STATUSRESERVA = 'CONVERTIDA'
WHERE IDRESERVA = 2;



-- COMANDOS DE UPDATE DE VEICULOS
--  ATUALIZAR quilometragem do veiculo locado
UPDATE VEICULO
SET KMATUAL = 45800
WHERE IDVEICULO = 9;


-- ATUALIZAR o status de veiculo para MANUTENCAO
UPDATE VEICULO
SET STATUSVEICULO = 'MANUTENCAO'
WHERE IDVEICULO = 14;



-- ATUALIZAR cor do veIculo
UPDATE VEICULO
SET COR = 'Preto Fosco'
WHERE IDVEICULO = 3;


-- TRANSFERIR veculo de filial
UPDATE VEICULO
SET IDFILIAL = 3
WHERE IDVEICULO = 11;


-- ATUALIZAR categoria DO VEICULO
UPDATE VEICULO
SET IDCATEGORIA = 5
WHERE IDVEICULO = 15;




-- COMANDOS DE DELETE de CLIENTES
-- DELETE Cadastro de CLIENTE DUPLICADO
DELETE FROM CLIENTE
WHERE CPF = '111.222.333-44';


-- DELETE CILENTE QUE QUIS TER SEU CADATRO EXCLUIDO 
DELETE FROM CLIENTE
WHERE IDCLIENTE = 10;


--  DELETE funcionario desligado
DELETE FROM FUNCIONARIO
WHERE IDFUNCIONARIO = 4;


-- DELETE cadastro incompleto de CLIENTE
DELETE FROM CLIENTE
WHERE EMAIL IS NULL AND TELEFONE IS NULL;


-- DELETE filial criada para teste
DELETE FROM FILIAL
WHERE IDFILIAL = 6;





-- COMANDOS DE DELETE DE RESERVAS
DELETE FROM RESERVA
WHERE IDRESERVA = 12;


-- DELETE DE reserva antiga 
DELETE FROM RESERVA
WHERE STATUSRESERVA = 'CANCELADA' AND IDRESERVA = 9;


-- DELETE reserva de teste
DELETE FROM RESERVA
WHERE IDCLIENTE = 1 AND DATAINICIO < '2024-01-01';


-- DELETE reservas expiradas
DELETE FROM RESERVA
WHERE DATAFIM < CURRENT_DATE - INTERVAL 90 DAY
AND STATUSRESERVA = 'ATIVA';


--  DELETE reserva duplicada
DELETE FROM RESERVA
WHERE IDRESERVA = 3;




-- COMANDOS DELETE DE VEICULO

-- DELETE VEICULO DUPLICADO
DELETE FROM VEICULO
WHERE PLACA = 'ABC1234';

--  DELETE VEICULO que foi vendido
DELETE FROM VEICULO
WHERE IDVEICULO = 18;


-- DELETE VEICULO de teste
DELETE FROM VEICULO
WHERE MARCA = 'TESTE'
AND MODELO = 'PROTO';


-- DELETE VEICULO sucateados
DELETE FROM VEICULO
WHERE STATUSVEICULO = 'TRANSFERENCIA'
AND KMATUAL = 0;


-- DELETE VEICULO cadastrado sem categoria
DELETE FROM VEICULO
WHERE IDCATEGORIA NOT IN (SELECT IDCATEGORIA FROM CATEGORIA);






